### ISSUE TITLE
ktera doesn't work please help 

### ISSUE THREAD

**Issue by badgon** [Gl0/CasualMeter#2]
![0101](https://cloud.githubusercontent.com/assets/17763211/15096388/56e36380-1530-11e6-9b1b-be1a6c76acc9.png)

**Comment by Gl0** [comment]
Be sure that you are using latest version. Autoupdate is not working in this beta, you need to download fresh version manually.

**Comment by badgon** [comment]
Casual_v1.1.0.7E  

![0101](https://cloud.githubusercontent.com/assets/17763211/15098252/61a81b06-1573-11e6-8806-b5fb6742cd8c.png)

q,.q

**Comment by Gl0** [comment]
That's strange, I've rechecked, it uses the same core and DB as latest shinra.

**Comment by Gl0** [comment]
Make sure, that your damage is not filtered by options like "ignore oneshots" and "count only bosses"

**Comment by badgon** [comment]
![0001](https://cloud.githubusercontent.com/assets/17763211/15098869/994f6320-1582-11e6-9bee-0994eaa19c2f.PNG)

Log file-----------
2016-05-09 00:22:04,581 [1] ERROR CasualMeter.App - System.Exception: Update.exe not found, not a Squirrel-installed app?
   위치: Squirrel.UpdateManager.getUpdateExe() 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 280
   위치: Squirrel.UpdateManager.getApplicationName() 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 259
   위치: Squirrel.UpdateManager..ctor(String urlOrPath, String applicationName, String rootDirectory, IFileDownloader urlDownloader) 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 41
   위치: CasualMeter.App.<Update>d__3.MoveNext() 파일 J:\c\CasualMeter\CasualMeter\App.xaml.cs:줄 61
2016-05-09 00:22:04,911 [1] INFO  CasualMeter.App - Starting up.
2016-05-09 00:22:07,011 [6] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-05-09 00:23:23,375 [10] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been disabled.
2016-05-09 00:23:23,607 [10] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-05-09 00:23:30,055 [12] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server 벨릭의 은총.
2016-05-09 00:27:35,176 [1] INFO  CasualMeter.App - Closing.
2016-05-09 00:57:55,119 [1] ERROR CasualMeter.App - System.Exception: Update.exe not found, not a Squirrel-installed app?
   위치: Squirrel.UpdateManager.getUpdateExe() 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 280
   위치: Squirrel.UpdateManager.getApplicationName() 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 259
   위치: Squirrel.UpdateManager..ctor(String urlOrPath, String applicationName, String rootDirectory, IFileDownloader urlDownloader) 파일 C:\Users\paulb\code\squirrel\squirrel.windows\src\Squirrel\UpdateManager.cs:줄 41
   위치: CasualMeter.App.<Update>d__3.MoveNext() 파일 J:\c\CasualMeter\CasualMeter\App.xaml.cs:줄 61
2016-05-09 00:57:55,219 [1] INFO  CasualMeter.App - Starting up.
2016-05-09 00:57:56,443 [6] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Sniffer has been enabled.
2016-05-09 00:58:23,989 [8] INFO  CasualMeter.Common.UI.ViewModels.CasualViewModelBase - Connected to server 벨릭의 은총.

**Comment by Gl0** [comment]
Error is from missing autoupdate files (seems I"ve compiled version with update check enabled), but next lines says that meter is successfully connected.
I can recompile it without update check, but that should not change anything.

**Comment by Gl0** [comment]
Replaced archive with autoupdate disabled version.

**Comment by badgon** [comment]
![0001](https://cloud.githubusercontent.com/assets/17763211/15099564/8b4d721a-1593-11e6-887c-6495bd38a29a.PNG)

Q,.Q

**Comment by Gl0** [comment]
Everything looks fine. Try to disable ignore oneshots filter. Shinra is working fine with this server now?

**Comment by badgon** [comment]
![012](https://cloud.githubusercontent.com/assets/17763211/15099665/997ae50e-1596-11e6-9810-457f85dd947b.PNG)

**Comment by Gl0** [comment]
You have modded shinra, may be it using more fresh opcodes than you [send us](https://github.com/neowutran/ShinraMeter/issues/119)?

**Comment by badgon** [comment]
@Gl0 http://tera.nexon.com/main/index.aspx          / id : casualmeter@gmail.com     / pw:casual$

test Account~

**Comment by Gl0** [comment]
I don't have KTera client, so it should take some time to get it

**Comment by badgon** [comment]
ok~

**Comment by Gl0** [comment]
Try Casual_v1.1.0.7F.zip

**Comment by badgon** [comment]
![0001](https://cloud.githubusercontent.com/assets/17763211/15103149/d0ac449a-15e2-11e6-9086-b7020698bbde.PNG)
thy thy thy~~~q,.q
